### ISSUE TITLE
Incorrect implementation of printHelpCommands method

### ISSUE THREAD

**Issue by kahlokkee** [AY1920S1-CS2113T-W17-4/main#73]
Reading of help manual from local storage should be done in the Storage class, not the Ui class. 

Referencing #70.

**Comment by debbiextan** [comment]
printHelpCommands method is now separated into readManual method in Storage class as well as printHelpCommands (commands Help function) and printHelpCommand (for individual command Help function) methods in Ui class. Will close this issue once the merge is complete.
